#!/usr/bin/env bash

DOMAIN=$1

print_func () {
	IP=$(nslookup $1.$DOMAIN | grep 'Address: *[0-9]' | cut -d ":" -f 2 | tr '\n' ' ')
	echo $IP | awk '{print "The subdomain " $1 " is a A record and points to" $IP}'
}

if [ $# -gt 1 ]; then
	IP=$(nslookup $2.$DOMAIN | grep 'Address: *[0-9]' | cut -d ":" -f 2 | tr '\n' ' ')
	echo $IP | awk '{print "The subdomain " $1 " is a A record and points to" $IP}'
else
	print_func "www"
	print_func "lb-01"
	print_func "web-01"
	print_func "web-02"
fi
