#!/usr/bin/env bash
# script that prints out remote server address from sub-domain

DOMAIN=$1

print_func () {
	IP=$(nslookup $1.$DOMAIN | grep 'Address: *[0-9]' | cut -d ":" -f 2 | tr '\n' ' ')
	echo "$1 $IP" | awk '{print "The subdomain " $1 " is a A record and points to " $2}'
}

if [ $# -gt 1 ]; then
	IP=$(nslookup $2.$DOMAIN | grep 'Address: *[0-9]' | cut -d ":" -f 2 | tr '\n' ' ')
	echo "$2 $IP" | awk '{print "The subdomain " $2 " is a A record and points to " $2}'
else
	print_func "www"
	print_func "lb-01"
	print_func "web-01"
	print_func "web-02"
fi
