#!/usr/bin/env bash
# install and configure a load balancer on a server

sudo apt-get -y update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*
sudo systemctl start haproxy

echo -e "
frontend myfrontend
	bind *:80
 	default_backend mybackend
  
backend mybackend
 	balance roundrobin
 	server 223183-web-01 18.233.66.148
	server 223183-web-02 54.236.184.219
" >> /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
