#!/usr/bin/env bash
# fizzbuzz implemetation

num=1

while [ $num -lt 101 ]; do
	if (( num % 15 == 0 )); then
		echo "FizzBuzz"
	elif (( num % 5 == 0 )); then
		echo "Buzz"
	elif (( num % 3 == 0 )); then
		echo "Fizz"
	else
		echo "$num"
	fi
	(( num++ ))
done
