#!/usr/bin/env bash
# script that displays time for 12 hours and 59 minutes

hrs=0
mins=1

while [ $hrs -lt 12 ] ; do
	echo "Hours: $hrs"
	while [ $mins -lt 60 ] ; do
		echo $mins
		(( mins++ ))
	done
	mins=1
	(( hrs++ ))
done
